USE `showdb`;

CREATE TABLE `praise` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) DEFAULT NULL,
  `panel_id` INT(11) DEFAULT NULL,
  `ispraise` INT(11) DEFAULT NULL,
  `createtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
